language: go

go:
  - tip

os:
  - linux
  - osx

sudo: false

install:
  - export GO15VENDOREXPERIMENT=1
  - export PATH=$GOPATH/bin:$PATH
  - echo $PATH
  - echo $GOPATH
  - echo $GO15VENDOREXPERIMENT
  - ls
  - go version
  - go env
  - go get github.com/tools/godep
  - godep restore
  # Build help
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes
  - conda install -y -q pip
  - pip install -r .ci/requirements.txt

script:
  - go test $(go list ./... | grep -v /vendor/)
  - go run main.go
  # Build
  - go build
  - ls
  # Upload
  - export VERSION=$(git describe --tags --dirty --always)
  - export NAME_VERSION=remote-conda-$VERSION
  - tar -zxvf $NAME_VERSION-$TRAVIS_OS_NAME.tar.gz remote-conda
  - ls
  - aws s3 cp $NAME_VERSION-$TRAVIS_OS_NAME.tar.gz s3://danielfrg-ci/remote-conda/
