version: "{build}"

os: Windows Server 2012 R2

environment:
  GOPATH: c:\gopath

clone_folder: c:\gopath\src\github.com\danielfrg\remote-conda

# Not a .NET project building on test_script
build: false

install:
  - echo %PATH%
  - echo %GOPATH%
  - ls
  - go version
  - go env
  - go get golang.org/x/crypto/ssh
  - go get github.com/codegangsta/cli

test_script:
  - go run main.go
  # Build
  - go build
  - 7z a remote-conda-%APPVEYOR_BUILD_NUMBER%.tar remote-conda.exe
  - ls

artifacts:
  - path: remote-conda-%APPVEYOR_BUILD_NUMBER%.tar
