version: "{build}"

os: Windows Server 2012 R2

environment:
  GOPATH: c:\gopath
  MINICONDA: C:\Miniconda3
  AWS_ACCESS_KEY_ID:
    secure: I/8C3iEP0maAqAJIOJxGC5NQavxZCN1W7wrInJRMlts=
  AWS_SECRET_ACCESS_KEY:
    secure: cSycCaMsrrbYY/IWG0tp2rlb1k6UvtPRUH9EHpv/3gONiX84rjfaA8rlyqeCjuDw

clone_folder: c:\gopath\src\github.com\danielfrg\remote-conda

# Not a .NET project building on test_script
build: false

install:
  - "set GO15VENDOREXPERIMENT=1"
  - "set PATH=%GOPATH%\\bin;%PATH%"
  - echo %PATH%
  - echo %GOPATH%
  - ls
  - go version
  - go env
  - go get github.com/tools/godep
  - godep restore
  # Build help
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda install -y -q pip
  - pip install -r .ci/requirements.txt

test_script:
  - go test $(go list ./... | grep -v /vendor/)
  - go run main.go
  # Build
  - go build
  - ls
  # Upload
  - for /f %%i in ('git describe --tags --dirty --always') do set VERSION=%%i
  - "set NAME_VERSION=remote-conda-%VERSION%"
  - 7z a %NAME_VERSION%-windows.tar remote-conda.exe
  - ls
  - aws s3 cp %NAME_VERSION%-windows.tar s3://danielfrg-ci/remote-conda/
