version: "{build}"

os: Windows Server 2012 R2

environment:
  GOPATH: c:\gopath
  MINICONDA: C:\Miniconda3
  AWS_ACCESS_KEY_ID:
    secure: TRYwHAB1P2wYKT9QrNq9/qSokTpA2abH0lJ9J5Q0bRU=
  AWS_SECRET_ACCESS_KEY:
    secure: fw2K412gLcP9yOixXLRBEEuOh35xL+oWMf80erFx

clone_folder: c:\gopath\src\github.com\danielfrg\remote-conda

# Not a .NET project building on test_script
build: false

install:
  - echo %PATH%
  - echo %GOPATH%
  - ls
  - go version
  - go env
  - go get golang.org/x/crypto/ssh
  - go get github.com/codegangsta/cli
  # Build help
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda install -y -q pip
  - pip install -r .ci/requirements.txt

test_script:
  - go run main.go
  # Build
  - go build
  - ls
  # Upload
  - for /f %%i in ('git describe --tags --dirty --always') do set VERSION=%%i
  - "set NAME_VERSION=remote-conda-%VERSION%"
  - 7z a %NAME_VERSION%-windows.tar remote-conda.exe
  - ls
  - aws s3 cp %NAME_VERSION%-windows.tar s3://danielfrg-ci/remote-conda/
