version: "{build}"

os: Windows Server 2012 R2

environment:
  GOPATH: c:\gopath

clone_folder: c:\gopath\src\github.com\danielfrg\remote-conda

# Not a .NET project
build: false

install:
  - echo %PATH%
  - echo %GOPATH%
  - go version
  - go env
  - go get golang.org/x/crypto/ssh
  - go get github.com/codegangsta/cli

test_script:
  - go run main.go
  - go build
	- ls
